version: "3"

services: 
    app:
        build: .
        ports:
            - 80:80
        env_file: 
            - .env
        depends_on: 
            - redis
    redis:
        image: redis:latest
        command: redis-server --appendonly yes
        volumes: 
            - dbdata:/data
        expose: 
            - 6379

volumes: 
    dbdata: